### ISSUE TITLE
Performance on 16 -beam lidar 

### ISSUE THREAD

**Issue by Jay-Karhade** [haomo-ai/OverlapTransformer#10]
Hi,
I recently read your work on Overlap Transformers and this is a really interesting approach! I was wondering if performance on 16-beam lidars was evaluated?

**Comment by BIT-MJY** [comment]
Hello @Jay-Karhade,

Thanks for your interest in our work!

We have only evaluated OT on 64/32-beam LiDAR datasets. If you want to implement OT for 16-beam LiDAR, you can modify the OverlapNetLeg and train the network from scratch.

**Comment by Jay-Karhade** [comment]
Thanks ! I will report the performance once i train . Closing this issue for now.
