### ISSUE TITLE
Loop Decetion

### ISSUE THREAD

**Issue by ydragon719** [haomo-ai/OverlapTransformer#17]
Your work has taught me a lot. Can SeqOT also be used for loop closure detection in SLAM?

**Comment by BIT-MJY** [comment]
Thanks for your interest in our work. SeqOT can recognize similar places so it can be used to find loops in SLAM. We recommend using our newer single-frame-based [CVTNet](https://github.com/BIT-MJY/CVTNet) to close loops with sota performance.
