### ISSUE TITLE
请问在test的时候生成query的描述子，将这个描述子和之前的描述子是如何匹配的？

### ISSUE THREAD

**Issue by shenyehui** [haomo-ai/OverlapTransformer#19]
作者，您好！test的过程是我理解的这样吗？先将query scan生成描述子，然后将他和之前的描述子匹配找到合适的candidate scan，再计算query scan和candidate scan的overlap来确定是否闭环。如果是这样的，请问描述子之间是如何匹配的，是看256维度的描述子是否一致吗？能否仅看描述子的匹配程度就确定是否闭环而不进一步计算overlap?

**Comment by BIT-MJY** [comment]
overlap是用来构建数据集的。我们直接使用描述子的距离来衡量点云相似度，也就是“仅看描述子的匹配程度就确定是否闭环”。

**Comment by shenyehui** [comment]
> overlap是用来构建数据集的。我们直接使用描述子的距离来衡量点云相似度，也就是“仅看描述子的匹配程度就确定是否闭环”。
非常感谢您的解答！

**Comment by BIT-MJY** [comment]
再次感谢关注我们的工作！我将关闭此issue。
