### ISSUE TITLE
format of depth image

### ISSUE THREAD

**Issue by NUDTherui** [haomo-ai/OverlapTransformer#22]
十分感谢作者的工作，请问为什么seqot的深度图保存为numpy格式而overlaptransformer的深度图保存为png格式，这两者之间对网络的训练测试有什么影响吗？
![屏幕截图 2023-05-26 111740](https://github.com/haomo-ai/OverlapTransformer/assets/100144648/2e467e99-db33-4e93-b560-075f74014b1e)
png格式
![屏幕截图 2023-05-26 111815](https://github.com/haomo-ai/OverlapTransformer/assets/100144648/a77b597b-2034-4b40-8acc-dd5cb3bfd470)
numpy格式

**Comment by Chen-Xieyuanli** [comment]
感谢关注我们的工作！这两个格式没有本质上的区别，深度图每个pixel只有一个值，用png或者npy保存都行，不同格式可能会影响python读取速度，但对深度图的读取而言，可以忽略不记。
