### ISSUE TITLE
HAOMO Dataset links

### ISSUE THREAD

**Issue by JBKnights** [haomo-ai/OverlapTransformer#24]
Hi,

Thanks for your excellent work- I was interested in downloading the HAOMO dataset for my own work, but the links appear to be broken.  Would you be able to fix these links or provide an alternative way to download?

Thank you,
Josh

**Comment by BIT-MJY** [comment]
Hello @JBKnights ,

Thanks for your interest in our work! Maybe the current Haomo server migration causes this. I will update the links once the migration is done.

**Comment by BIT-MJY** [comment]
Hi @JBKnights , Thanks for your patience! The links are updated and you can download the data now.
