### ISSUE TITLE
train-set的一些疑问？

### ISSUE THREAD

**Issue by SHUNLU-1** [haomo-ai/OverlapTransformer#28]
**首先，非常感谢你们的十分优秀的项目。**

1.对于train_set的建立，目前我根据你的建议使用OverlapNet中demo4_gen_gt_files，也对于每帧数据进行计算了。

![2023-12-08_16-33](https://github.com/haomo-ai/OverlapTransformer/assets/59217928/d307dd08-521d-4045-9d13-50c91a980f2e)
计算的是kitti的04序列(271个) ，但是我目前根据com_overlap_yaw和normalize_data得到的dist_norm_data是(9100, 4)以及根据split_train_val得到的train_data(8190, 4)和validation_data(910, 4)，与我读到你们分享的04的train_data(2674,)差异很大
，请问一下我的处理哪里出现问题了？可以分享一下你们的处理代码吗？

2.对于你的其他两个项目(CVTNet和SeqOT)对于我的数据集效果不佳(我的数据类似地下车库的重复场景)，使用你的预训练模型(未对我的数据集微调)，想问问你有什么好的建议或者改进的地方？

**期待你的回复！**

**Comment by SHUNLU-1** [comment]
谢谢你的回复与帮助
1.对于seqot(more_chosen_normalized_data_120108.npy),存在28127个数据，more_chosen_normalized_data_120108的shape为(115000, 3)，请问你们more_chosen_normalized_data_120108如何生成？
2.目前需要实现的是相对long-term长时间跨度下的全局定位，解决存在很多重复场景丢失后重定位的问题。

**Comment by BIT-MJY** [comment]
1. 您可以normalize数据的分布到(115000, 3)，通过这个[程序](https://github.com/BIT-MJY/SeqOT/blob/main/data_prepararion/gen_training_index.py)
2. 确实有些gap存在，建议重新生成RIV和BEV并finetune  CVTNet。主要原因是(1)应用场景不同导致gap。我们的模型是在地上的机器人载32线雷达上训练的，行驶环境为校园环境，与车辆在地下车库行驶情况差距非常大。(2)激光雷达型号和安装位置不同也会导致gap。比如线束分布不同和雷达安装高度不同导致range image生成方式的差异。

**Comment by SHUNLU-1** [comment]
十分感谢你的帮助，我尝试对模型微调。
