### ISSUE TITLE
方便提供百度云的预训练模型权重文件吗？(pretrained models in Baiduyun)

### ISSUE THREAD

**Issue by oym1994** [haomo-ai/OverlapTransformer#3]
谢谢大佬们的大作，膜拜膜拜

        可以提供百度云链接的权重文件（libtorch和pytorch版本均需）吗？国内木得梯子

非常感谢！！

**Comment by BIT-MJY** [comment]
Hello @oym1994 ,

感谢支持我们的工作，我已经上传了我们的预训练权重至百度云，链接如下：

[pretrained_overlap_transformer.pth.tar](https://pan.baidu.com/s/1EroRZiu4CDFgFUMKTVD_Bg)  --- 提取码：kftk  

[overlapTransformer.pt](https://pan.baidu.com/s/1Kky242ev42KgoRpziVGpdQ)  --- 提取码：qhmg

**Comment by oym1994** [comment]
好的，再次非常感谢

**Comment by oym1994** [comment]
您好，请问可以再提供cpu推理的模型吗？电脑还没得gpu， 谢谢啦

**Comment by BIT-MJY** [comment]
目前我们的预训练模型只有基于gpu训练的，cpu训练将耗费过多时间。
