### ISSUE TITLE
training tensors

### ISSUE THREAD

**Issue by yanlong95** [haomo-ai/OverlapTransformer#30]
Hi there,

I'm sorry for bother you again during the break.

I'm wondering why you set the input tensor requires_grad as true here https://github.com/haomo-ai/OverlapTransformer/blob/ddf61d6b43fbc3a0e747a8f10d8330b409adff02/train/training_overlap_transformer_kitti.py#L156

As I understand, the input_batch are tensors of the range images which should not be modified in the training step (although do not impact the optimization since they are not added in the optimizer).

Appreciate your time and help.

**Comment by BIT-MJY** [comment]
Hi @yanlong95 , Thanks for pointing out the redundancy code in our released version. We have removed this line.
