### ISSUE TITLE
关于Haomo数据集

### ISSUE THREAD

**Issue by LY0406** [haomo-ai/OverlapTransformer#34]
您好，感谢您出色的开源工作，通过您给出的数据文件以及代码，我已经成功在KITTI数据集上复现了您的工作，我想在Haomo数据集上也进行实现，并且希望在我自己的工作中用到该数据集，您已经提供了Haomo数据集的scans文件以及poses文件，我应该如何生成train_set以及ground truth呢？如果您在OT代码中给出了生成KITTI sequence00的train_set以及groundt truth文件的代码，我想通过这个代码来生成train_set，但是并没有calib.txt文件，请问对与Haomo数据集来说生成train_set是否需要calib.txt文件，以及您是否会发布关于Haomo数据集的train_set和ground truth文件。
再次感谢您的开源工作！

**Comment by wangzihanggg** [comment]
请问可以交流下吗 我的微信是wangzihangggg

**Comment by LY0406** [comment]
我已经申请你加你好友了，备注Github发自我的 iPhone在 2024年7月9日，00:46，ZihangWang ***@***.***> 写道：﻿
请问可以交流下吗 我的微信是wangzihangggg

**Comment by BIT-MJY** [comment]
合并至此[issue](https://github.com/haomo-ai/OverlapTransformer/issues/36)。
