### ISSUE TITLE
如何生成FordCampus数据集的环视图？

### ISSUE THREAD

**Issue by wangzihanggg** [haomo-ai/OverlapTransformer#35]
@BIT-MJY 感谢您的工作对我的研究带来的启发！
我遵循了你的方法使用wget  https://s3.us-east-2.amazonaws.com/ford.perl.engin.umich.edu/dataset-1.tar.gz下载了数据集 里面的Velodyne雷达的保存形式是pcap格式的，我如何将这种格式的雷达数据转化为和kitti一样的bin文件以便后续生成环视图？

**Comment by BIT-MJY** [comment]
Hi @wangzihanggg 
感谢关注我们的工作！您可以直接使用[我们此前生成的range image](https://drive.google.com/file/d/1TDsFqbyTg2DYeeRuK8amd9dHDU9OAwLM/view?usp=sharing)。

**Comment by wangzihanggg** [comment]
> Hi @wangzihanggg 感谢关注我们的工作！您可以直接使用[我们此前生成的range image](https://drive.google.com/file/d/1TDsFqbyTg2DYeeRuK8amd9dHDU9OAwLM/view?usp=sharing)。

感谢您的回复！我已经在FC数据集上复现成功。

**Comment by wangzihanggg** [comment]
感谢您的迅速回复！ @BIT-MJY 
我已经在FC数据集上复现成功。我将继续在haomo数据集上进行研究。
