### ISSUE TITLE
16线激光雷达支持(16 line lidar support)

### ISSUE THREAD

**Issue by oym1994** [haomo-ai/OverlapTransformer#4]
您好，方便提供支持16线激光雷达的配置吗？目前测试16线激光雷达数据时显示输入尺寸问题。

此外， 当输入为1800 32的激光雷达数据时， 描述子的尺寸为[2, 256]， 说明网络输出的描述子尺寸是受输入尺寸影响的？

谢谢！！！

**Comment by oym1994** [comment]
好的，谢谢您的热情回复，我们尝试尝试

**Comment by fkp0918** [comment]
您好，请问您尝试了16线雷达的训练吗，相应训练所需的16线雷达数据集请问您知道如何获取吗？

**Comment by BIT-MJY** [comment]
正如上面所说，我们并未使用16线雷达进行训练和测试，您可以简单地将64/32线雷达数据集降采样得到16线数据集。

**Comment by Jay-Karhade** [comment]
嗨，如果你测试过，我可以知道 16 光束激光雷达的性能吗？
